#!/bin/bash


cd source/yl/lib/yl

ragel -o yl_parser_ragel.cpp yl_parser_ragel.rl
sed -i '' 's|yl_parser_ragel\.rl|../../toolbox/source/yl/lib/parser/yl_parser_ragel.rl|g' yl_parser_ragel.cpp

lemon yl_parser_lemon.y
mv yl_parser_lemon.c yl_parser_lemon.cpp
sed -i '' 's|yl_parser_lemon\.y|../../toolbox/source/yl/lib/parser/yl_parser_lemon.y|g' yl_parser_lemon.cpp
sed -i '' 's|yl_parser_lemon\.c|../../toolbox/source/yl/lib/parser/yl_parser_lemon.cpp|g' yl_parser_lemon.cpp

cd ../../../..


