#define LEMON_IF                              1
#define LEMON_ELSE                            2
#define LEMON_TRY                             3
#define LEMON_CATCH                           4
#define LEMON_FINALLY                         5
#define LEMON_YIELD                           6
#define LEMON_LPN                             7
#define LEMON_IDENTIFIER                      8
#define LEMON_COMMA                           9
#define LEMON_ELLIPSIS                       10
#define LEMON_PERIOD                         11
#define LEMON_LBR                            12
#define LEMON_RBR                            13
#define LEMON_DEF                            14
#define LEMON_COLON                          15
#define LEMON_SEMICOLON                      16
#define LEMON_RPN                            17
#define LEMON_VAR                            18
#define LEMON_ASSIGN                         19
#define LEMON_LSQ                            20
#define LEMON_RSQ                            21
#define LEMON_NEW                            22
#define LEMON_NULL                           23
#define LEMON_TRUE                           24
#define LEMON_FALSE                          25
#define LEMON_NUMBER                         26
#define LEMON_STRING                         27
#define LEMON_INCREMENT                      28
#define LEMON_DECREMENT                      29
#define LEMON_PLUS                           30
#define LEMON_MINUS                          31
#define LEMON_XMARK                          32
#define LEMON_TILDE                          33
#define LEMON_ASTERISK                       34
#define LEMON_SOLIDUS                        35
#define LEMON_PERCENT                        36
#define LEMON_LSHIFT                         37
#define LEMON_LRSHIFT                        38
#define LEMON_ARSHIFT                        39
#define LEMON_AMPERSAND                      40
#define LEMON_CARET                          41
#define LEMON_VBAR                           42
#define LEMON_CONCATENATE                    43
#define LEMON_EQUAL                          44
#define LEMON_NOTEQUAL                       45
#define LEMON_LESS                           46
#define LEMON_GREATER                        47
#define LEMON_LESSEQUAL                      48
#define LEMON_GREATEREQUAL                   49
#define LEMON_IN                             50
#define LEMON_NOTIN                          51
#define LEMON_IS                             52
#define LEMON_NOTIS                          53
#define LEMON_LOGICAND                       54
#define LEMON_LOGICXOR                       55
#define LEMON_LOGICOR                        56
#define LEMON_QMARK                          57
#define LEMON_MULASSIGN                      58
#define LEMON_DIVASSIGN                      59
#define LEMON_MODASSIGN                      60
#define LEMON_INTDIVASSIGN                   61
#define LEMON_ADDASSIGN                      62
#define LEMON_SUBASSIGN                      63
#define LEMON_LSHIFTASSIGN                   64
#define LEMON_LRSHIFTASSIGN                  65
#define LEMON_ARSHIFTASSIGN                  66
#define LEMON_BITANDASSIGN                   67
#define LEMON_BITXORASSIGN                   68
#define LEMON_BITORASSIGN                    69
#define LEMON_WHILE                          70
#define LEMON_DELETE                         71
#define LEMON_CASE                           72
#define LEMON_DEFAULT                        73
#define LEMON_CONTINUE                       74
#define LEMON_BREAK                          75
#define LEMON_RETURN                         76
#define LEMON_THROW                          77
#define LEMON_SWITCH                         78
#define LEMON_DO                             79
#define LEMON_FOR                            80
#define LEMON_EACHKEY                        81
#define LEMON_USING                          82
