#define LEMON_IF                              1
#define LEMON_ELSE                            2
#define LEMON_TRY                             3
#define LEMON_CATCH                           4
#define LEMON_FINALLY                         5
#define LEMON_YIELD                           6
#define LEMON_LPN                             7
#define LEMON_IDENTIFIER                      8
#define LEMON_FUNCTION                        9
#define LEMON_OBJECT                         10
#define LEMON_COMMA                          11
#define LEMON_ELLIPSIS                       12
#define LEMON_PERIOD                         13
#define LEMON_LBR                            14
#define LEMON_RBR                            15
#define LEMON_COLON                          16
#define LEMON_SEMICOLON                      17
#define LEMON_RPN                            18
#define LEMON_VAR                            19
#define LEMON_ASSIGN                         20
#define LEMON_LSQ                            21
#define LEMON_RSQ                            22
#define LEMON_NEW                            23
#define LEMON_NULL                           24
#define LEMON_TRUE                           25
#define LEMON_FALSE                          26
#define LEMON_NUMBER                         27
#define LEMON_STRING                         28
#define LEMON_INCREMENT                      29
#define LEMON_DECREMENT                      30
#define LEMON_PLUS                           31
#define LEMON_MINUS                          32
#define LEMON_XMARK                          33
#define LEMON_TILDE                          34
#define LEMON_ASTERISK                       35
#define LEMON_SOLIDUS                        36
#define LEMON_PERCENT                        37
#define LEMON_LSHIFT                         38
#define LEMON_LRSHIFT                        39
#define LEMON_ARSHIFT                        40
#define LEMON_AMPERSAND                      41
#define LEMON_CARET                          42
#define LEMON_VBAR                           43
#define LEMON_CONCATENATE                    44
#define LEMON_EQUAL                          45
#define LEMON_NOTEQUAL                       46
#define LEMON_LESS                           47
#define LEMON_GREATER                        48
#define LEMON_LESSEQUAL                      49
#define LEMON_GREATEREQUAL                   50
#define LEMON_IN                             51
#define LEMON_NOTIN                          52
#define LEMON_IS                             53
#define LEMON_NOTIS                          54
#define LEMON_LOGICAND                       55
#define LEMON_LOGICXOR                       56
#define LEMON_LOGICOR                        57
#define LEMON_QMARK                          58
#define LEMON_MULASSIGN                      59
#define LEMON_DIVASSIGN                      60
#define LEMON_MODASSIGN                      61
#define LEMON_INTDIVASSIGN                   62
#define LEMON_ADDASSIGN                      63
#define LEMON_SUBASSIGN                      64
#define LEMON_LSHIFTASSIGN                   65
#define LEMON_LRSHIFTASSIGN                  66
#define LEMON_ARSHIFTASSIGN                  67
#define LEMON_BITANDASSIGN                   68
#define LEMON_BITXORASSIGN                   69
#define LEMON_BITORASSIGN                    70
#define LEMON_WHILE                          71
#define LEMON_DELETE                         72
#define LEMON_CASE                           73
#define LEMON_DEFAULT                        74
#define LEMON_CONTINUE                       75
#define LEMON_BREAK                          76
#define LEMON_RETURN                         77
#define LEMON_THROW                          78
#define LEMON_SWITCH                         79
#define LEMON_DO                             80
#define LEMON_FOR                            81
#define LEMON_EACHKEY                        82
#define LEMON_USING                          83
