#define LEMON_IF                              1
#define LEMON_ELSE                            2
#define LEMON_TRY                             3
#define LEMON_CATCH                           4
#define LEMON_FINALLY                         5
#define LEMON_YIELD                           6
#define LEMON_LPN                             7
#define LEMON_IDENTIFIER                      8
#define LEMON_PERIOD                          9
#define LEMON_RPN                            10
#define LEMON_RBR                            11
#define LEMON_LBR                            12
#define LEMON_COLON                          13
#define LEMON_SEMICOLON                      14
#define LEMON_VAR                            15
#define LEMON_ASSIGN                         16
#define LEMON_COMMA                          17
#define LEMON_LSQ                            18
#define LEMON_RSQ                            19
#define LEMON_NEW                            20
#define LEMON_NULL                           21
#define LEMON_TRUE                           22
#define LEMON_FALSE                          23
#define LEMON_NUMBER                         24
#define LEMON_STRING                         25
#define LEMON_INCREMENT                      26
#define LEMON_DECREMENT                      27
#define LEMON_PLUS                           28
#define LEMON_MINUS                          29
#define LEMON_XMARK                          30
#define LEMON_TILDE                          31
#define LEMON_ASTERISK                       32
#define LEMON_SOLIDUS                        33
#define LEMON_PERCENT                        34
#define LEMON_LSHIFT                         35
#define LEMON_LRSHIFT                        36
#define LEMON_ARSHIFT                        37
#define LEMON_AMPERSAND                      38
#define LEMON_CARET                          39
#define LEMON_VBAR                           40
#define LEMON_CONCATENATE                    41
#define LEMON_EQUAL                          42
#define LEMON_NOTEQUAL                       43
#define LEMON_LESS                           44
#define LEMON_GREATER                        45
#define LEMON_LESSEQUAL                      46
#define LEMON_GREATEREQUAL                   47
#define LEMON_IN                             48
#define LEMON_NOTIN                          49
#define LEMON_IS                             50
#define LEMON_NOTIS                          51
#define LEMON_LOGICAND                       52
#define LEMON_LOGICXOR                       53
#define LEMON_LOGICOR                        54
#define LEMON_QMARK                          55
#define LEMON_ELLIPSIS                       56
#define LEMON_MULASSIGN                      57
#define LEMON_DIVASSIGN                      58
#define LEMON_MODASSIGN                      59
#define LEMON_INTDIVASSIGN                   60
#define LEMON_ADDASSIGN                      61
#define LEMON_SUBASSIGN                      62
#define LEMON_LSHIFTASSIGN                   63
#define LEMON_LRSHIFTASSIGN                  64
#define LEMON_ARSHIFTASSIGN                  65
#define LEMON_BITANDASSIGN                   66
#define LEMON_BITXORASSIGN                   67
#define LEMON_BITORASSIGN                    68
#define LEMON_WHILE                          69
#define LEMON_DELETE                         70
#define LEMON_CASE                           71
#define LEMON_DEFAULT                        72
#define LEMON_CONTINUE                       73
#define LEMON_BREAK                          74
#define LEMON_RETURN                         75
#define LEMON_THROW                          76
#define LEMON_SWITCH                         77
#define LEMON_DO                             78
#define LEMON_FOR                            79
#define LEMON_EACHKEY                        80
#define LEMON_USING                          81
