#define LEMON_SEMICOLON                       1
#define LEMON_IDENTIFIER                      2
#define LEMON_PERIOD                          3
#define LEMON_LPN                             4
#define LEMON_RPN                             5
#define LEMON_LBR                             6
#define LEMON_RBR                             7
#define LEMON_COLON                           8
#define LEMON_YIELD                           9
#define LEMON_LSQ                            10
#define LEMON_RSQ                            11
#define LEMON_NUMBER                         12
#define LEMON_STRING                         13
#define LEMON_TRUE                           14
#define LEMON_FALSE                          15
#define LEMON_NULL                           16
#define LEMON_PLUS                           17
#define LEMON_MINUS                          18
#define LEMON_XMARK                          19
#define LEMON_TILDE                          20
#define LEMON_ASTERISK                       21
#define LEMON_SOLIDUS                        22
#define LEMON_PERCENT                        23
#define LEMON_LSHIFT                         24
#define LEMON_RSHIFT                         25
#define LEMON_URSHIFT                        26
#define LEMON_AMPERSAND                      27
#define LEMON_CARET                          28
#define LEMON_VBAR                           29
#define LEMON_EQUAL                          30
#define LEMON_NOTEQUAL                       31
#define LEMON_LESS                           32
#define LEMON_GREATER                        33
#define LEMON_LESSEQUAL                      34
#define LEMON_GREATEREQUAL                   35
#define LEMON_IN                             36
#define LEMON_NOTIN                          37
#define LEMON_IS                             38
#define LEMON_NOTIS                          39
#define LEMON_LOGICAND                       40
#define LEMON_LOGICXOR                       41
#define LEMON_LOGICOR                        42
#define LEMON_QMARK                          43
#define LEMON_NEW                            44
#define LEMON_COMMA                          45
#define LEMON_ELLIPSIS                       46
#define LEMON_ASSIGN                         47
#define LEMON_MULASSIGN                      48
#define LEMON_DIVASSIGN                      49
#define LEMON_MODASSIGN                      50
#define LEMON_INTDIVASSIGN                   51
#define LEMON_ADDASSIGN                      52
#define LEMON_SUBASSIGN                      53
#define LEMON_LSHIFTASSIGN                   54
#define LEMON_RSHIFTASSIGN                   55
#define LEMON_URSHIFTASSIGN                  56
#define LEMON_BITANDASSIGN                   57
#define LEMON_BITXORASSIGN                   58
#define LEMON_BITORASSIGN                    59
#define LEMON_BREAK                          60
#define LEMON_CASE                           61
#define LEMON_CATCH                          62
#define LEMON_CONTINUE                       63
#define LEMON_DEFAULT                        64
#define LEMON_DO                             65
#define LEMON_ELSE                           66
#define LEMON_FINALLY                        67
#define LEMON_FOR                            68
#define LEMON_IF                             69
#define LEMON_RETURN                         70
#define LEMON_SWITCH                         71
#define LEMON_THROW                          72
#define LEMON_TRY                            73
#define LEMON_USING                          74
#define LEMON_VAR                            75
#define LEMON_WHILE                          76
#define LEMON_INCREMENT                      77
#define LEMON_DECREMENT                      78
