#define LEMON_IF                              1
#define LEMON_ELSE                            2
#define LEMON_TRY                             3
#define LEMON_CATCH                           4
#define LEMON_FINALLY                         5
#define LEMON_LPN                             6
#define LEMON_RPN                             7
#define LEMON_LBR                             8
#define LEMON_RBR                             9
#define LEMON_IDENTIFIER                     10
#define LEMON_PERIOD                         11
#define LEMON_COMMA                          12
#define LEMON_COLON                          13
#define LEMON_YIELD                          14
#define LEMON_VAR                            15
#define LEMON_SEMICOLON                      16
#define LEMON_ASSIGN                         17
#define LEMON_LSQ                            18
#define LEMON_RSQ                            19
#define LEMON_NUMBER                         20
#define LEMON_STRING                         21
#define LEMON_TRUE                           22
#define LEMON_FALSE                          23
#define LEMON_NULL                           24
#define LEMON_PLUS                           25
#define LEMON_MINUS                          26
#define LEMON_XMARK                          27
#define LEMON_TILDE                          28
#define LEMON_ASTERISK                       29
#define LEMON_SOLIDUS                        30
#define LEMON_PERCENT                        31
#define LEMON_LSHIFT                         32
#define LEMON_RSHIFT                         33
#define LEMON_URSHIFT                        34
#define LEMON_AMPERSAND                      35
#define LEMON_CARET                          36
#define LEMON_VBAR                           37
#define LEMON_EQUAL                          38
#define LEMON_NOTEQUAL                       39
#define LEMON_LESS                           40
#define LEMON_GREATER                        41
#define LEMON_LESSEQUAL                      42
#define LEMON_GREATEREQUAL                   43
#define LEMON_IN                             44
#define LEMON_NOTIN                          45
#define LEMON_IS                             46
#define LEMON_NOTIS                          47
#define LEMON_LOGICAND                       48
#define LEMON_LOGICXOR                       49
#define LEMON_LOGICOR                        50
#define LEMON_QMARK                          51
#define LEMON_NEW                            52
#define LEMON_ELLIPSIS                       53
#define LEMON_MULASSIGN                      54
#define LEMON_DIVASSIGN                      55
#define LEMON_MODASSIGN                      56
#define LEMON_INTDIVASSIGN                   57
#define LEMON_ADDASSIGN                      58
#define LEMON_SUBASSIGN                      59
#define LEMON_LSHIFTASSIGN                   60
#define LEMON_RSHIFTASSIGN                   61
#define LEMON_URSHIFTASSIGN                  62
#define LEMON_BITANDASSIGN                   63
#define LEMON_BITXORASSIGN                   64
#define LEMON_BITORASSIGN                    65
#define LEMON_SWITCH                         66
#define LEMON_CASE                           67
#define LEMON_DEFAULT                        68
#define LEMON_WHILE                          69
#define LEMON_DO                             70
#define LEMON_FOR                            71
#define LEMON_EACHKEY                        72
#define LEMON_CONTINUE                       73
#define LEMON_BREAK                          74
#define LEMON_RETURN                         75
#define LEMON_USING                          76
#define LEMON_THROW                          77
#define LEMON_INCREMENT                      78
#define LEMON_DECREMENT                      79
