#define LEMON_IF                              1
#define LEMON_ELSE                            2
#define LEMON_TRY                             3
#define LEMON_CATCH                           4
#define LEMON_FINALLY                         5
#define LEMON_YIELD                           6
#define LEMON_USING                           7
#define LEMON_LPN                             8
#define LEMON_RPN                             9
#define LEMON_LBR                            10
#define LEMON_RBR                            11
#define LEMON_IDENTIFIER                     12
#define LEMON_PERIOD                         13
#define LEMON_COMMA                          14
#define LEMON_COLON                          15
#define LEMON_VAR                            16
#define LEMON_SEMICOLON                      17
#define LEMON_ASSIGN                         18
#define LEMON_LSQ                            19
#define LEMON_RSQ                            20
#define LEMON_NEW                            21
#define LEMON_NUMBER                         22
#define LEMON_STRING                         23
#define LEMON_TRUE                           24
#define LEMON_FALSE                          25
#define LEMON_NULL                           26
#define LEMON_INCREMENT                      27
#define LEMON_DECREMENT                      28
#define LEMON_PLUS                           29
#define LEMON_MINUS                          30
#define LEMON_XMARK                          31
#define LEMON_TILDE                          32
#define LEMON_ASTERISK                       33
#define LEMON_SOLIDUS                        34
#define LEMON_PERCENT                        35
#define LEMON_LSHIFT                         36
#define LEMON_RSHIFT                         37
#define LEMON_URSHIFT                        38
#define LEMON_AMPERSAND                      39
#define LEMON_CARET                          40
#define LEMON_VBAR                           41
#define LEMON_CONCATENATE                    42
#define LEMON_EQUAL                          43
#define LEMON_NOTEQUAL                       44
#define LEMON_LESS                           45
#define LEMON_GREATER                        46
#define LEMON_LESSEQUAL                      47
#define LEMON_GREATEREQUAL                   48
#define LEMON_IN                             49
#define LEMON_NOTIN                          50
#define LEMON_IS                             51
#define LEMON_NOTIS                          52
#define LEMON_LOGICAND                       53
#define LEMON_LOGICXOR                       54
#define LEMON_LOGICOR                        55
#define LEMON_QMARK                          56
#define LEMON_ELLIPSIS                       57
#define LEMON_MULASSIGN                      58
#define LEMON_DIVASSIGN                      59
#define LEMON_MODASSIGN                      60
#define LEMON_INTDIVASSIGN                   61
#define LEMON_ADDASSIGN                      62
#define LEMON_SUBASSIGN                      63
#define LEMON_LSHIFTASSIGN                   64
#define LEMON_RSHIFTASSIGN                   65
#define LEMON_URSHIFTASSIGN                  66
#define LEMON_BITANDASSIGN                   67
#define LEMON_BITXORASSIGN                   68
#define LEMON_BITORASSIGN                    69
#define LEMON_DELETE                         70
#define LEMON_SWITCH                         71
#define LEMON_CASE                           72
#define LEMON_DEFAULT                        73
#define LEMON_WHILE                          74
#define LEMON_DO                             75
#define LEMON_FOR                            76
#define LEMON_EACHKEY                        77
#define LEMON_CONTINUE                       78
#define LEMON_BREAK                          79
#define LEMON_RETURN                         80
#define LEMON_THROW                          81
